### ISSUE TITLE
Errors when trying to start a stream from private channel.

### ISSUE THREAD

**Issue by dkwiebe** [alephcom/MusicPlayer#1]
Telegram says: [400 USER_IS_BOT] - A bot cannot send messages to other bots or to itself (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/home/listentochurch/MusicPlayer/core/stream.py", line 95, in start_stream
    await pytgcalls.join_group_call(
  File "/home/listentochurch/.local/lib/python3.8/site-packages/pytgcalls/methods/groups/join_group_call.py", line 213, in join_group_call
    raise NoActiveGroupCall()
pytgcalls.exceptions.NoActiveGroupCall: No active group call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -HIDDEN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/listentochurch/MusicPlayer/core/decorators.py", line 108, in decorator
    return await func(client, obj, *args)
  File "main.py", line 167, in live_stream
    await start_stream(song, lang)
  File "/home/listentochurch/MusicPlayer/core/stream.py", line 101, in start_stream
    peer = await app.resolve_peer(chat.id)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 109, in resolve_peer
    await self.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/listentochurch/MusicPlayer/core/decorators.py", line 38, in decorator
    return await func(client, message, *args)
  File "/home/listentochurch/MusicPlayer/core/decorators.py", line 56, in decorator
    return await func(client, obj, lang)
  File "/home/listentochurch/MusicPlayer/core/decorators.py", line 116, in decorator
    await pyro_client.send_message(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
    r = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UserIsBot: Telegram says: [400 USER_IS_BOT] - A bot cannot send messages to other bots or to itself (caused by "messages.SendMessage")

**Comment by dkwiebe** [comment]
It looks like that behaviour is caused when only the bot and not the user as well are added as admins to a channel.

pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

**Comment by collab-smart** [comment]
Hi @dkwiebe 
In .env file,  we can set suoders (telegram user id) for sending detailed error messages to the user.
This error occured when the configuration does not exist. so you can skip it
![image](https://user-images.githubusercontent.com/63889804/161056172-303b2ec4-d898-4660-888a-8a6c0ca6e6e5.png)
.

**Comment by dkwiebe** [comment]
I see, that would work for now.  I'll try setting a sudo user.
